{"name": "Тестируем ошибку входа с неправильным логином. Ручка /v1/courier/login", "status": "passed", "start": 1758393461773, "stop": 1758393461905, "uuid": "feed34bf-87e1-4d6f-a91d-945101693343", "historyId": "5ae90ce696050e993d40a8b921dd9749", "testCaseId": "5ae90ce696050e993d40a8b921dd9749", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "NIK-T14"}, {"name": "thread", "value": "20952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestLoginCourier"]}